version: '3.8'
services:
  app:
    build:
      context: .
    volumes:
      - .:/rails:rw
      - ./log:/rails/log:rw
      - ./config:/rails/config:rw
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/myapp_development
    depends_on:
      - db
    user: "root"
    networks:
      - ruby

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ruby

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - ruby

  memcached:
    image: memcached:alpine
    ports:
      - "11211:11211"
    networks:
      - ruby

networks:
  ruby:
    driver: bridge

volumes:
  postgres_data: